spring:
  profiles:
    active: local
  application:
    name: demo-oauth-webmvc
server:
  port: 8082
logging:
  config: classpath:config/logback.xml
logback:
  file-path: ${user.dir}/logs
custom:
  hmac256: abcdefghijklmnop
  users:
    - usercode: zhangsan
      password: zhangsan
      username: 张三
      age: 19
      sex: A
      address: dddddddddd
    - usercode: lisi
      password: lisi
      username: 李四
      age: 21
      sex: A
      address: gggggggg
    - usercode: xiaojuan
      password: xiaojuan
      username: 小娟
      age: 22
      sex: V
      address: eeeeeeee
